global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAURBAL4NXBTEFO7JQ
        secret_key: 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
        port: 9100
